version: 1.0.{build}

image: Visual Studio 2019

build_script:
  - npm install
  - npm run watch
  - npm run ip
  
artifacts:
  - path: build
    name: my-app

deploy:
  - provider: GitHub
    artifact: my-app
    draft: true
